name: Deploy to Lambda 1

on:
 
  push:
    branches: [ main ]
    tags: 
      - lambda_1

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:



    - name: Check out code
      uses: actions/checkout@v2
    
    # - name: install pytest
    #   run: | 
    #     pip3 install pytest
    # - name: run testing
    #   run: | 
    #     pytest


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t 156058766667.dkr.ecr.eu-west-1.amazonaws.com/team_yogurt:latest -t 156058766667.dkr.ecr.eu-west-1.amazonaws.com/team_yogurt:21July2022 .
        docker push 156058766667.dkr.ecr.eu-west-1.amazonaws.com/team_yogurt:latest
        docker push 156058766667.dkr.ecr.eu-west-1.amazonaws.com/team_yogurt:21July2022
        
    - name: Update Lambda
      run: |
        aws lambda update-function-code --function-name yogurt-retrival-lambda --image-uri 156058766667.dkr.ecr.eu-west-1.amazonaws.com/team_yogurt:latest


        

